### ISSUE TITLE
Does security-intro project works, for me it dont, there no compilor error but only runtime errors, please fix it

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [TrainingByPackt/Beginning-Springboot#3]
Lesson 8-Web Application Security/security-intro/

**Comment by orlovskyjavaprofi** [comment]
2019-05-08 13:22:18.116  WARN 6124 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'homePageController' defined in file [L:\ProgrammingStuff\JAVA\STS-Projects\BookProjects\SpringBoot2Fundamentals\security-intro\target\classes\com\packt\springboot\securityintro\logic\HomePageController.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.packt.springboot.securityintro.logic.HomePageController]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems: 
	The blank final field overAnnotatedService may not have been initialized
	The blank final field sms may not have been initialized
	log cannot be resolved
	Type mismatch: cannot convert from Authentication to val
	The method getAuthorities() is undefined for the type val
	The method getPrincipal() is undefined for the type val
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved

2019-05-08 13:22:18.120  INFO 6124 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-05-08 13:22:18.135  INFO 6124 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-08 13:22:18.146 ERROR 6124 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'homePageController' defined in file [L:\ProgrammingStuff\JAVA\STS-Projects\BookProjects\SpringBoot2Fundamentals\security-intro\target\classes\com\packt\springboot\securityintro\logic\HomePageController.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.packt.springboot.securityintro.logic.HomePageController]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems: 
	The blank final field overAnnotatedService may not have been initialized
	The blank final field sms may not have been initialized
	log cannot be resolved
	Type mismatch: cannot convert from Authentication to val
	The method getAuthorities() is undefined for the type val
	The method getPrincipal() is undefined for the type val
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1238) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1137) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at com.packt.springboot.securityintro.SecurityIntroApplication.main(SecurityIntroApplication.java:10) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.3.RELEASE.jar:2.0.3.RELEASE]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.packt.springboot.securityintro.logic.HomePageController]: Constructor threw exception; nested exception is java.lang.Error: Unresolved compilation problems: 
	The blank final field overAnnotatedService may not have been initialized
	The blank final field sms may not have been initialized
	log cannot be resolved
	Type mismatch: cannot convert from Authentication to val
	The method getAuthorities() is undefined for the type val
	The method getPrincipal() is undefined for the type val
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved

	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1230) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 22 common frames omitted
Caused by: java.lang.Error: Unresolved compilation problems: 
	The blank final field overAnnotatedService may not have been initialized
	The blank final field sms may not have been initialized
	log cannot be resolved
	Type mismatch: cannot convert from Authentication to val
	The method getAuthorities() is undefined for the type val
	The method getPrincipal() is undefined for the type val
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved
	log cannot be resolved

	at com.packt.springboot.securityintro.logic.HomePageController.<init>(HomePageController.java:21) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_202]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_202]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 24 common frames omitted

**Comment by pcornelissen** [comment]
This looks like lombok is not working or present. Can you check on your end?

**Comment by orlovskyjavaprofi** [comment]
hm, i think i didn't used lombok, in my project lombok quite can be quite abigious dependency.

**Comment by pcornelissen** [comment]
```
pcornelissen@moneysink:~/projects/test/3$ git clone git@github.com:TrainingByPackt/Spring-Boot-2-Fundamentals.git
pcornelissen@moneysink:~/projects/test/3$ cd Spring-Boot-2-Fundamentals/Lesson\ 8-Web\ Application\ Security/security-intro/

$ mvn package
...
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.018 s
[INFO] Finished at: 2019-05-09T13:17:34+02:00
[INFO] ------------------------------------------------------------------------

$ mvn spring-boot:run
...
2019-05-09 13:18:33.389  INFO 10679 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2019-05-09 13:18:33.430  INFO 10679 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2019-05-09 13:18:33.434  INFO 10679 --- [  restartedMain] c.p.s.s.SecurityIntroApplication         : Started SecurityIntroApplication in 2.15 seconds (JVM running for 2.412)

```

By default lombok is included, if you have removed it, you need to create all the getters/setters and construnctors etc. by hand.
Lombok is a compile time only dependency and does only what you tell it to. I don't see the harm in that.
You might see the error you have copied in here when you try to start the software from your IDE when the lombok plugin is not present/working and the IDE doesn't use maven to build the software. 

I am pretty sure your problem is related to your project/IDE setup. As you can see the code I just checked out works fine without any change.

**Comment by orlovskyjavaprofi** [comment]
pcornelissen yes it was my mistake, i dont use for my pet projects intelij, i use STS Eclipse.
My frontend use in memory data-structure i dont think to persist it directly to database, i think i will use rest to send post request to my backend, in my backend which will be a close source project i do then the persistence.
When i work for client i use ide which my client use in his project, but anyway thanks for advise . When i got the error i was like wtf , wtf then i installed lombok plugin into my eclipse and well it works.
